server:
  port: 9000
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false #不在eureka注册自己
    fetch-registry: false #不从eureka获取注册信息
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
